name: Update values.yaml on image push

on:
  repository_dispatch:
    types: [update-image-tag]

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Update values.yaml
        run: |
          IMAGE_URL="${{ github.event.client_payload.image_url }}"
          echo "Updating values.yaml with image: $IMAGE_URL"
          sed -i "s|image: .*|image: $IMAGE_URL|" charts/frontend/values.yaml

      - name: Commit and push
        run: |
          git add charts/frontend/values.yaml
          git commit -m "Update image to $IMAGE_URL from CI"
          git push